from . import account_invoice
from . import account_invoice_line
from . import product_category
from . import product_template
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import taxjar_config
from . import taxjar_product_code
